-- ZCity — Silah İsimleri Türkçe Çeviri
-- Sadece PrintName override edilir, başka hiçbir şeye dokunulmaz.

local names = {
    -- Otomatik Tüfekler
    ["weapon_ak74"]             = "AK-74",
    ["weapon_ak74u"]            = "AKS-74U",
    ["weapon_ak200"]            = "AK-200",
    ["weapon_ak203"]            = "AK-203",
    ["weapon_akm"]              = "AKM",
    ["weapon_akmwreked"]        = "Yeraltı AKM",
    ["weapon_ar15"]             = "AR-15",
    ["weapon_ar_pistol"]        = "AR-15 Tabanca",
    ["weapon_ac556"]            = "Ruger AC-556",
    ["weapon_ash12"]            = "ASH-12",
    ["weapon_asval"]            = "AS «Val»",
    ["weapon_hk416"]            = "HK416",
    ["weapon_m4a1"]             = "M4A1",
    ["weapon_m4super"]          = "Benelli M4 Super 90",
    ["weapon_m16a2"]            = "M16A2",
    ["weapon_sg552"]            = "SG 552 Commando",
    ["weapon_vpo136"]           = "VPO-136",
    ["weapon_vpo209"]           = "VPO-209",
    ["weapon_sok94"]            = "Vepr SOK-94-03",
    ["weapon_draco"]            = "Micro Draco",
    ["weapon_dracovska"]        = "VSKA Draco",
    ["weapon_ab10"]             = "AB-10",
    ["weapon_osipr"]            = "O.S.I.P.R.",
    ["weapon_pluviska"]         = "Pluviska",
    ["weapon_slugcat"]          = "SLUGCAT",

    -- Keskin Nişancı / Yarı Otomatik Tüfekler
    ["weapon_svd"]              = "SVD",
    ["weapon_sr25"]             = "SR25",
    ["weapon_m98b"]             = "Barrett M98B",
    ["weapon_sks"]              = "SKS",
    ["weapon_mini14"]           = "Mini-14",
    ["weapon_ruger"]            = "Ruger 10/22",
    ["weapon_mosin"]            = "Mosin-Nagant M38",
    ["weapon_kar98"]            = "Karabiner 98k",
    ["weapon_ptrd"]             = "PTRD-41",
    ["weapon_ptrd_fun_auto"]    = "PTRD-41 Tam Otomatik",
    ["weapon_musket"]           = "Long Land Pattern",
    ["weapon_combinesniper"]    = "Combine KN Tüfeği",
    ["weapon_osipr"]            = "O.S.I.P.R.",

    -- Pompalı / Yarım Otomatik Tüfekler
    ["weapon_remington870"]     = "Remington 870",
    ["weapon_remington870_roullet"] = "KUMARBAZ TÜFEK",
    ["weapon_saiga12"]          = "Saiga-12",
    ["weapon_spas12"]           = "Franchi SPAS-12",
    ["weapon_m590a1"]           = "Mossberg 590A1",
    ["weapon_xm1014"]           = "XM-1014",
    ["weapon_doublebarrel"]     = "İJ-43",
    ["weapon_doublebarrel_short"] = "İJ-43 Kısaltılmış",
    ["weapon_ks23"]             = "KS-23",
    ["weapon_toz106"]           = "TOZ-106",

    -- Hafif Makineliler / Makineli
    ["weapon_pkm"]              = "PKM",
    ["weapon_rpk"]              = "RPK-74",
    ["weapon_m249"]             = "M249",
    ["weapon_m60"]              = "M60",
    ["weapon_hk21"]             = "HK21",
    ["weapon_kord"]             = "Kord 6P50",
    ["weapon_ags_30_handheld"]  = "AGS-30",

    -- SMG / Hafif Tüfekler
    ["weapon_mp5"]              = "HK MP5",
    ["weapon_mp7"]              = "HK MP7",
    ["weapon_p90"]              = "FN P90",
    ["weapon_mac11"]            = "MAC-11",
    ["weapon_uzi"]              = "Uzi",
    ["weapon_vector"]           = "KRISS Vector",
    ["weapon_tmp"]              = "Steyr TMP",
    ["weapon_skorpion"]         = "Šcorpion vz. 61",
    ["weapon_colt9mm"]          = "Colt 9mm SMG",
    ["weapon_pm9"]              = "PM-9",
    ["weapon_mp_80"]            = "MP-80-13T",

    -- Tabancalar
    ["weapon_glock17"]          = "Glock 17",
    ["weapon_glock18c"]         = "Glock 18C",
    ["weapon_glock26"]          = "Glock 26",
    ["weapon_deagle"]           = "Desert Eagle",
    ["weapon_cz75"]             = "ČZ 75",
    ["weapon_cz75a"]            = "ČZ 75-A",
    ["weapon_m1911"]            = "Colt M1911",
    ["weapon_m45"]              = "Colt M45A1",
    ["weapon_m9beretta"]        = "Beretta M9",
    ["weapon_px4beretta"]       = "Beretta PX4",
    ["weapon_fn45"]             = "FNX-45",
    ["weapon_browninghp"]       = "Browning Hi-Power",
    ["weapon_hk_usp"]           = "HK USP",
    ["weapon_makarov"]          = "Makarov Tabancası",
    ["weapon_tokarev"]          = "TT-33",
    ["weapon_p22"]              = "Walther P22",
    ["weapon_pl15"]             = "PL-15",
    ["weapon_revolver2"]        = "Manurhin MR-96",
    ["weapon_revolver357"]      = "Colt King Cobra",
    ["weapon_tec9"]             = "TEC-9",
    ["weapon_flintlock"]        = "Süvari Tabancası",
    ["weapon_fury13"]           = "Fury-13",
    ["weapon_osapb"]            = "PB-4 Osa",
    ["weapon_zoraki"]           = "Zoraki Stalker M906",
    ["weapon_taser"]            = "Taser X26",
    ["weapon_tranquilizer"]     = "Uyutucu Tabanca",

    -- Patlayıcılar / Bomba
    ["weapon_hg_rgd_tpik"]      = "RGD-5 El Bombası",
    ["weapon_hg_grenade_tpik"]  = "M67 El Bombası",
    ["weapon_hg_f1_tpik"]       = "F1 El Bombası",
    ["weapon_hg_type59_tpik"]   = "Tip-59 El Bombası",
    ["weapon_hg_hl2nade_tpik"]  = "Combine El Bombası",
    ["weapon_hg_flashbang_tpik"] = "Taş",
    ["weapon_hg_smokenade_tpik"] = "Güherçile Sis Bombası",
    ["weapon_hg_molotov_tpik"]  = "Molotov Kokteyli",
    ["weapon_hg_pipebomb_tpik"] = "Boru Bombası",
    ["weapon_hg_slam"]          = "SLAM",
    ["weapon_claymore"]         = "Claymore",
    ["weapon_breachcharge"]     = "Kapı Kırma Şarjı",
    ["weapon_traitor_ied"]      = "El Yapımı Patlayıcı",
    ["weapon_hg_rpg"]           = "RPG-7",
    ["weapon_hg_rebelrpg"]      = "İsyancı RPG'si",

    -- Kesici / Yakın Dövüş
    ["weapon_melee"]            = "Muharebe Bıçağı",
    ["weapon_pocketknife"]      = "Çakı",
    ["weapon_sogknife"]         = "SOG SEAL 2000",
    ["weapon_buck200knife"]     = "Buck 120 Bıçağı",
    ["weapon_hg_machete"]       = "Pala",
    ["weapon_tomahawk"]         = "Tomahawk",
    ["weapon_hg_spear"]         = "Mızrak",
    ["weapon_hg_spear_knife"]   = "Bıçaklı Mızrak",
    ["weapon_hg_spear_pro"]     = "Gelişmiş Mızrak",
    ["weapon_hg_shuriken"]      = "Shuriken",
    ["weapon_hg_bow"]           = "\"Geyik Avcısı\" Yayı",
    ["weapon_hg_crossbow"]      = "El Yapımı Arbalest",
    ["weapon_hg_axe"]           = "Odun Baltası",
    ["weapon_hatchet"]          = "Balta",
    ["weapon_hg_sledgehammer"]  = "Balyoz",
    ["weapon_hg_shovel"]        = "Kürek",
    ["weapon_hg_crowbar"]       = "Levye",
    ["weapon_hg_crowbar_gordon"] = "Levye",

    -- Sopa / Künt Silahlar
    ["weapon_bat"]              = "Beyzbol Sopası",
    ["weapon_hammer"]           = "Çekiç",
    ["weapon_leadpipe"]         = "Kurşun Boru",
    ["weapon_pan"]              = "Tava",
    ["weapon_brick"]            = "Tuğla",
    ["weapon_chair_leg"]        = "Sandalye Ayağı",
    ["weapon_table_leg"]        = "Masa Ayağı",
    ["weapon_gymnasticstick"]   = "Jimnastik Sopası",
    ["weapon_ram"]              = "Kapı Koçbaşı",
    ["weapon_hg_tonfa"]         = "Polis Tonfası",
    ["weapon_hg_stunstick"]     = "Elektrikli Cop",

    -- Kırık / Çeşitli Nesneler
    ["weapon_hg_bottle"]        = "Şişe",
    ["weapon_hg_bottlebroken"]  = "Kırık Şişe",
    ["weapon_hg_glassshard"]    = "Cam Kırığı",
    ["weapon_hg_glassshard_taped"] = "Bantlı Cam Kırığı",
    ["weapon_hg_mug"]           = "Kupa",

    -- Tıbbi
    ["weapon_bandage_sh"]       = "Sargı Bezi",
    ["weapon_bigbandage_sh"]    = "Büyük Sargı Bezi",
    ["weapon_medkit_sh"]        = "Tıbbi Çanta",
    ["weapon_bloodbag"]         = "Kan Torbası",
    ["weapon_tourniquet"]       = "Turnike",
    ["weapon_morphine"]         = "Morfin",
    ["weapon_fentanyl"]         = "Fentanil",
    ["weapon_adrenaline"]       = "Epinefrin Enjektörü",
    ["weapon_fury16"]           = "Norepinefrin (Güçlü)",
    ["weapon_betablock"]        = "Beta-Bloker",
    ["weapon_naloxone"]         = "Nalokson",
    ["weapon_mannitol"]         = "Mannitol",
    ["weapon_thiamine"]         = "Tiamin",
    ["weapon_painkillers"]      = "Ağrı Kesici",
    ["weapon_painkillers_tpik"] = "Ağrı Kesici",
    ["weapon_needle"]           = "Dekompresyon İğnesi",
    ["weapon_medkit"]           = "İlk Yardım Çantası",

    -- Zehir / Katil Özel
    ["weapon_traitor_poison1"]  = "Tetrodotoksin Şırıngası",
    ["weapon_traitor_poison2"]  = "VX Flakon",
    ["weapon_traitor_poison3"]  = "Siyanür Tüpü",
    ["weapon_traitor_poison4"]  = "Curare Flakon",
    ["weapon_traitor_poison_consumable"] = "Siyanür Kapsülü",
    ["weapon_traitor_suit"]     = "Kılık",

    -- Sarf Malzeme / Tüketilebilir
    ["weapon_smallconsumable"]  = "Küçük Sarf Malzeme",
    ["weapon_smallconsumable_tpik"] = "Küçük Sarf Malzeme",
    ["weapon_bigconsumable"]    = "Büyük Sarf Malzeme",
    ["weapon_bigconsumable_tpik"] = "Büyük Sarf Malzeme",
    ["weapon_ducttape"]         = "Koli Bandı",
    ["weapon_matches"]          = "Kibrit Kutusu",
    ["weapon_hg_bugbait"]       = "\"Böcek Yemi\" Feromon",

    -- Ekipman / Diğer
    ["weapon_hands_sh"]         = "Eller",
    ["weapon_handcuffs"]        = "Kelepçe",
    ["weapon_handcuffs_key"]    = "Kelepçe Anahtarı",
    ["weapon_shield"]           = "Balistik Kalkan",
    ["weapon_grapplinghook"]    = "Kanca",
    ["weapon_hidebox"]          = "Katlanır Kutu",
    ["weapon_hg_jam"]           = "Kapı Takozı",
    ["weapon_hg_motiontracker"] = "Hareket Sensörü",
    ["weapon_hg_extinguisher"]  = "Yangın Söndürücü",
    ["weapon_walkie_talkie"]    = "Telsiz",
    ["weapon_spawnmenu_pda"]    = "Tablet",
    ["weapon_hg_coolhands"]     = "Soğuk Eller",
    ["weapon_hg_snowball"]      = "Kartopu",
    ["weapon_winchester"]       = "Winchester 1894",
    ["weapon_musket"]           = "Long Land Pattern",
    ["weapon_flintlock"]        = "Süvari Tabancası",
}

for class, turkishName in pairs(names) do
    local tbl = weapons.Get(class)
    if tbl then
        tbl.PrintName = turkishName
    end
end
